### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by heqds** [JohnTwentyTwo/Valorant-Checker-Fullcapture#3]
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(Running in a virtual Machine since I'm not 100% how much I trust)

I know a bit of python but not a lot in the slightest so what does this error mean? When installing requirements,  ctypes failed to install.

**Comment by Camt4372** [comment]
추가로

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\Desktop\Valorant-Checker-Fullcapture-main\sw1nhv2.4.py", line 474, in <module>
    checker()
  File "c:\Users\user\Desktop\Valorant-Checker-Fullcapture-main\sw1nhv2.4.py", line 234, in checker
    data = r2.json()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by liwe0** [comment]
same prob, any fix ?

**Comment by mediax1** [comment]
If you're running into issues like the `ctypes` error with newer Python versions, it's likely due to recent changes in the interpreter. Downgrading to an earlier version (e.g. Python 3.10 or 3.11) often resolves the problem. Save yourself the headache—downgrade now, thank me later.

**Comment by fritsbosse** [comment]
So im 3 years late but i dont understand how to install the  
python -m pip install colorama
python -m pip install requests
python -m pip install pandas
python -m pip install ctypes
Please help and ty

**Comment by heqds** [comment]
it's very likely years outdated, i don't even think it's worth the hassle. i remember it not working well once i got it going

**Comment by fritsbosse** [comment]
Oh well do you have one that does work?
